baseURL = "https://journal.jackpurrin.me"
theme = "bearneo"
title = "jackpurrin's digital journal"
languageCode = "en-US"
enableRobotsTXT = false
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/p/:slug"
  tags = "/blog/:slug"
[params]
  title = "jackpurrin's digital journal"
  description = "a website on the web for a cat on the internet to write his thoughts and feelings"
  favicon = "assets/img/favicon.png"
  images = ["images/share.png"]
  copyright = "Copyright © 2024-2025, jackpurrin."
  groupByYear = true
  showPostCount = true
  postSearch = false
  toc = true
  upvote = true
  upvoteURL = "https://vote.jackpurrin.me/" 

  [params.footer]
    hideCopyright = false
    hideSitemap = false
    hideMadeWithLine = true
    hideRSSAndEmail = false

  [params.RSS]
    enableRSS = true
    pageLimit = 10

  [params.author]
    name = "jackpurrin"
    email = "me@jackpurrin.me"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
